name: experiment
mode: imc
seed: 42

model:
  in_sz: 2000
  out_sz: 2000
  latent_sz: 20
  num_batch: 1
  bio_encoder_layers: [500, 2000, 2000]
  batch_encoder_layers: [500]
  decoder_layers: [2000, 2000, 500]
  bio_classifier_layers: [500, 2000, 2000]
  batch_classifier_layers: [128]
  dropout: 0.3

loss:
  recon: 10.0
  discriminator: 0.3
  classifier: 1.0
  kl_bio: 0.001
  kl_batch: 0.1
  ortho: 0.01
  kl_size: 0.002

trainer:
  epochs: 100
  batch_size: 128
  lr: 0.001
  weight_decay: 0.00001
  scheduler_step: 50
  scheduler_gamma: 0.1
  early_stop: 15
  save_dir: ./saved/
  save_period: 20
  verbosity: 2
  sampling_fraction: 1.0
  eval_seed: 42
