_base_: base.yaml
name: imc_experiment
mode: imc

model:
  in_sz: 38
  out_sz: 38
  num_batch: 12

loss:
  recon: 10.0
  discriminator: 0.3
  classifier: 1.0
  kl_bio: 0.001
  kl_batch: 0.1
  ortho: 0.01
