name: macaque
n_gpu: 1
seed: null

arch:
  type: GeneVAE
  args:
    in_sz: 2000
    bio_encoder_hidden_layers: [500, 2000, 2000]
    batch_encoder_hidden_layers: [500]
    latent_sz: 20
    decoder_hidden_layers: [2000, 2000, 500]
    # decoder_hidden_layers: [500, 2000, 2000]
    out_sz: 2000
    batch_classifier_layers_power: [500, 2000, 2000]
    batch_classifier_layers_weak: [128]
    num_batch: 4
    cell_classifier_layers: [64, 32]
    num_cells: 5
    unsupervised: True
    alpha: 1.0
    vamp_encoder_args:
      input_size: 2000
      z1_size: 20
      z2_size: 20
      number_components: 12

data_loader:
  type: Immune
  args:
    dataset: null  
    batch_size: 128
    shuffle: true
    num_workers: 2

optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0.00001
    amsgrad: true

loss: nll_loss

metrics:
  - accuracy
  - top_k_acc

lr_scheduler:
  type: StepLR
  args:
    step_size: 50
    gamma: 0.1

trainer:
  epochs: 81
  save_dir: "saved/"
  save_period: 20
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 10
  if_imc: False
  loss_weights:
    recon_loss: 5
    batch_loss_z1: 0.03
    batch_loss_z2: 0.1
    kl_loss_1: 0.00002
    kl_loss_2: 0.01
    ortho_loss: 0.001
    kl_loss_size: 0.01
